/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author carol
 */
public class Calculator2x2 extends javax.swing.JFrame {

    public void my_update(String str) {
        greeting.setText(str);
    }

    /**
     * Creates new form Calculator2x2
     */
    public Calculator2x2() {
        initComponents();
    }

    Calculator2x2(String text) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        greeting = new javax.swing.JLabel();
        y1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        x1 = new javax.swing.JTextField();
        r1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        y2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        x2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        r2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        resultX = new javax.swing.JLabel();
        calculateBtn = new javax.swing.JButton();
        resultY = new javax.swing.JLabel();
        clearBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jLabel13.setText("jLabel13");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Linear Equations Calculator");

        greeting.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        greeting.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        greeting.setText("greeting");

        y1.setPreferredSize(new java.awt.Dimension(35, 26));

        jLabel4.setText("x +");

        x1.setPreferredSize(new java.awt.Dimension(35, 26));

        r1.setPreferredSize(new java.awt.Dimension(35, 26));

        jLabel5.setText("y =");

        y2.setPreferredSize(new java.awt.Dimension(35, 26));

        jLabel6.setText("x +");

        x2.setPreferredSize(new java.awt.Dimension(35, 26));

        jLabel7.setText("y =");

        r2.setPreferredSize(new java.awt.Dimension(35, 26));
        r2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                r2KeyPressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setText("Result:");

        saveBtn.setText("Save");
        saveBtn.setPreferredSize(new java.awt.Dimension(100, 29));
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        backBtn.setText("Back");
        backBtn.setPreferredSize(new java.awt.Dimension(100, 29));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel14.setText("1.");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel15.setText("2.");

        resultX.setText("   ");

        calculateBtn.setText("Calculate");
        calculateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateBtnActionPerformed(evt);
            }
        });

        resultY.setText("   ");

        clearBtn.setText("Clear All");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Please type the constants for the following equations:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(greeting, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(calculateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(x1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(y1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(r1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(x2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(y2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(r2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(resultX)
                                .addGap(10, 10, 10)
                                .addComponent(resultY))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(clearBtn)
                                .addGap(18, 18, 18)
                                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(greeting)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(x1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(y1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(r1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(x2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(y2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(r2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(calculateBtn)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(resultX)
                    .addComponent(resultY))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearBtn)
                    .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        String str = greeting.getText();
        RegularUserMenu obj = new RegularUserMenu();
        obj.my_update(str);
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void calculateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateBtnActionPerformed

        if (x1.getText().matches("[a-zA-Z]+") || y1.getText().matches("[a-zA-Z]+") || r1.getText().matches("[a-zA-Z]+")
                || x2.getText().matches("[a-zA-Z]+") || y2.getText().matches("[a-zA-Z]+") || r2.getText().matches("[a-zA-Z]+")) {

            JOptionPane.showMessageDialog(null, "Enter a number; characters and symbols are not allowed.");

        } else {

            try {

                float[][] originalEquation = new float[2][2];
                float[] resultColum = new float[2];
                float[][] detAEquation = new float[2][2];
                float detA;
                float[][] inverse = new float[2][2];
                float[] results = new float[2];

                originalEquation[0][0] = Float.parseFloat(x1.getText());
                originalEquation[0][1] = Float.parseFloat(y1.getText());
                resultColum[0] = Float.parseFloat(r1.getText());
                originalEquation[1][0] = Float.parseFloat(x2.getText());
                originalEquation[1][1] = Float.parseFloat(y2.getText());
                resultColum[1] = Float.parseFloat(r2.getText());

                detA = (originalEquation[0][0] * originalEquation[1][1]) - (originalEquation[0][1] * originalEquation[1][0]);

                if (detA == 0) {
                    JOptionPane.showMessageDialog(null, "Determinante is 0. It is not possible calculate the variables values.");

                } else {

                    detAEquation[0][0] = originalEquation[1][1];
                    detAEquation[0][1] = originalEquation[0][1] * -1;
                    detAEquation[1][1] = originalEquation[0][0];
                    detAEquation[1][0] = originalEquation[1][0] * -1;

                    for (int row = 0; row < detAEquation.length; row++) {
                        for (int col = 0; col < detAEquation[row].length; col++) {
                            inverse[row][col] = (1 / detA) * detAEquation[row][col];
                        }
                    }

                    results[0] = (inverse[0][0] * resultColum[0]) + (inverse[0][1] * resultColum[1]);
                    results[1] = (inverse[1][0] * resultColum[0]) + (inverse[1][1] * resultColum[1]);

                    DecimalFormat df = new DecimalFormat("####0.00");
                    resultX.setText("(" + df.format(results[0]) + " ;");
                    resultY.setText(df.format(results[1]) + ")");

                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error.");
            }

        }

    }//GEN-LAST:event_calculateBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed

        x1.setText("");
        y1.setText("");
        r1.setText("");
        x2.setText("");
        y2.setText("");
        r2.setText("");
        resultX.setText("");
        resultY.setText("");

    }//GEN-LAST:event_clearBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed

        try {

            if (resultX.getText().isEmpty() || resultY.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Nothing to save.");

            } else {

                int user_id = 0;
                String first_equation = (x1.getText() + "x + " + y1.getText() + "y = " + r1.getText());
                String second_equation = (x2.getText() + "x + " + y2.getText() + "y = " + r2.getText());
                String result = (resultX.getText() + resultY.getText());

                //loads the database driver
                Class.forName("com.mysql.cj.jdbc.Driver");

                //retrieves and stores the query
                String selectUser = "SELECT user_id FROM user WHERE username=?";
                String insertOperation = "INSERT INTO operations (user_id, first_equation, second_equation, result) VALUES (?, ?, ?, ?)";

                //gets a connection to the database
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/users", "root", "*Dun04061620");

                //gets a statement from the connection
                PreparedStatement pstUser = conn.prepareStatement(selectUser);

                pstUser.setString(1, greeting.getText());

                //executes the query
                ResultSet rs = pstUser.executeQuery();

                if (rs.next()) {
                    user_id = rs.getInt("user_id");
                }

                PreparedStatement pstOperation = conn.prepareStatement(insertOperation);

                pstOperation.setInt(1, user_id);
                pstOperation.setString(2, first_equation);
                pstOperation.setString(3, second_equation);
                pstOperation.setString(4, result);
                pstOperation.execute();

                JOptionPane.showMessageDialog(null, "Operation saved!");

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_saveBtnActionPerformed

    private void r2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_r2KeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            if (x1.getText().matches("[a-zA-Z]+") || y1.getText().matches("[a-zA-Z]+") || r1.getText().matches("[a-zA-Z]+")
                    || x2.getText().matches("[a-zA-Z]+") || y2.getText().matches("[a-zA-Z]+") || r2.getText().matches("[a-zA-Z]+")) {

                JOptionPane.showMessageDialog(null, "Enter a number; characters and symbols are not allowed.");

            } else {

                try {

                    float[][] originalEquation = new float[2][2];
                    float[] resultColum = new float[2];
                    float[][] detAEquation = new float[2][2];
                    float detA;
                    float[][] inverse = new float[2][2];
                    float[] results = new float[2];

                    originalEquation[0][0] = Float.parseFloat(x1.getText());
                    originalEquation[0][1] = Float.parseFloat(y1.getText());
                    resultColum[0] = Float.parseFloat(r1.getText());
                    originalEquation[1][0] = Float.parseFloat(x2.getText());
                    originalEquation[1][1] = Float.parseFloat(y2.getText());
                    resultColum[1] = Float.parseFloat(r2.getText());

                    detA = (originalEquation[0][0] * originalEquation[1][1]) - (originalEquation[0][1] * originalEquation[1][0]);

                    if (detA == 0) {
                        JOptionPane.showMessageDialog(null, "Determinante is 0. It is not possible calculate the variables values.");

                    } else {

                        detAEquation[0][0] = originalEquation[1][1];
                        detAEquation[0][1] = originalEquation[0][1] * -1;
                        detAEquation[1][1] = originalEquation[0][0];
                        detAEquation[1][0] = originalEquation[1][0] * -1;

                        for (int row = 0; row < detAEquation.length; row++) {
                            for (int col = 0; col < detAEquation[row].length; col++) {
                                inverse[row][col] = (1 / detA) * detAEquation[row][col];
                            }
                        }

                        results[0] = (inverse[0][0] * resultColum[0]) + (inverse[0][1] * resultColum[1]);
                        results[1] = (inverse[1][0] * resultColum[0]) + (inverse[1][1] * resultColum[1]);

                        DecimalFormat df = new DecimalFormat("####0.00");
                        resultX.setText("(" + df.format(results[0]) + " ;");
                        resultY.setText(df.format(results[1]) + ")");

                    }

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Error.");
                }

            }

        }

    }//GEN-LAST:event_r2KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator2x2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator2x2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator2x2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator2x2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator2x2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    protected javax.swing.JButton calculateBtn;
    private javax.swing.JButton clearBtn;
    private javax.swing.JLabel greeting;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    protected javax.swing.JTextField r1;
    protected javax.swing.JTextField r2;
    private javax.swing.JLabel resultX;
    private javax.swing.JLabel resultY;
    private javax.swing.JButton saveBtn;
    protected javax.swing.JTextField x1;
    protected javax.swing.JTextField x2;
    protected javax.swing.JTextField y1;
    protected javax.swing.JTextField y2;
    // End of variables declaration//GEN-END:variables
}
